# https://taskfile.dev

version: '3'

silent: true


tasks:
  default:
    cmds:
      - task --list-all

  check:
    desc: Run all project checks
    cmds:
      - echo "- Run all routines"
      - task: tidy
      - task: tools:install
      - task: generate
      - task: fmt
      - task: lint
      - task: install
      - task: tests

  tidy:
    cmds:
      - echo "- Tidy"
      - go mod tidy

  fmt:
    desc: Run code formatter
    cmds:
      - echo "- Format"
      - go fmt ./...

  tools:install:
    desc: Install required tools (into local project dir)
    run: once
    cmds:
      - echo "- Run install tools"
      - go run github.com/kazhuravlev/toolset/cmd/toolset@latest sync

  generate:
    desc: Generate code
    env:
      SEARCH_BIN_PATH:
        sh: "echo `pwd`/{{ .TOOL_BIN_DIR }}:$PATH"
    cmds:
      - echo "- Generate code"
      - go generate ./...

  lint:
    desc: Run linter
    deps:
      - "tools:install"
    cmds:
      - echo "- Lint"
      - toolset run golangci-lint run --fix ./...

  install:
    run: once
    cmds:
      - echo "- Install"
      - go install ./cmd/structspec

  tests:
    cmds:
      - echo "- Tests"
      - go test -race -count 1 ./...
