// Code generated by structspec. DO NOT EDIT.
package {{ .PackageName }}

type Field string

// String implements Stringer interface
func (f Field) String() string {return string(f)}
// S - short version of String
func (f Field) S() string                   { return string(f) }

{{ range .Structs }}
	{{ $struct := . }}

	{{/* Render struct for each tag */}}
	{{ range .Tags -}}
		type {{ $struct.Name }}{{.Name}}Spec struct {
			{{ range .Fields -}}
				{{.Name}} Field
			{{end}}
		}
	{{ end }}

	{{/* Render struct which contains all "tag structs" from prev step */}}
	type {{ .Name }}Spec struct {
		{{ range .Tags -}}
			{{ .Name }} {{ $struct.Name }}{{.Name}}Spec
		{{ end }}
	}

    // {{ .Name }}F is short version of {{ .Name }}{}.F()
    func {{ .Name }}F() {{ .Name }}Spec {
    	return {{ .Name }}Spec{
            {{ range .Tags -}}
                {{.Name}}: {{ $struct.Name }}{{.Name}}Spec{
                    {{ range .Fields -}}
                        {{.Name}}: "{{.Value}}",
                    {{end}}
                },
            {{ end }}
    	}
    }

    // F returns fields spec for struct {{ .Name }}
    func ({{ .Name }}) F() {{ .Name }}Spec {
        return {{ .Name }}F()
    }
{{ end }}
