// Code generated by structspec. DO NOT EDIT.
package {{ .PackageName }}

type Field string

// String implements Stringer interface
func (f Field) String() string {return string(f)}
// S - short version of String
func (f Field) S() string                   { return string(f) }

{{ range .Structs }}

type {{ .Name }}Spec struct {
     {{ range .Fields -}}
		{{ .Name }} Field
	{{ end }}
}

// F returns fields spec for struct {{ .Name }}
func ({{ .Name }}) F() {{ .Name }}Spec {
	return {{ .Name }}F()
}

// {{ .Name }}F is short version of {{ .Name }}{}.F()
func {{ .Name }}F() {{ .Name }}Spec {
	return {{ .Name }}Spec{
		{{ range .Fields -}}
            {{ .Name }}: "{{ .Name }}",
		{{ end }}
	}
}

{{ end }}
