// Code generated by options-gen. DO NOT EDIT.
package impl

type OptOptionsSetter func(o *Options)

func NewOptions(
	options ...OptOptionsSetter,
) Options {
	o := Options{}

	// Setting defaults from field tag (if present)

	for _, opt := range options {
		opt(&o)
	}
	return o
}

func WithSource(opt string) OptOptionsSetter {
	return func(o *Options) {
		o.source = opt
	}
}

func WithIncludeStructs(opt []string) OptOptionsSetter {
	return func(o *Options) {
		o.includeStructs = opt
	}
}

func WithIgnoreStructs(opt []string) OptOptionsSetter {
	return func(o *Options) {
		o.ignoreStructs = opt
	}
}

func WithTags(opt []string) OptOptionsSetter {
	return func(o *Options) {
		o.tags = opt
	}
}

func WithOutPackage(opt string) OptOptionsSetter {
	return func(o *Options) {
		o.outPackage = opt
	}
}

func WithOutFilename(opt string) OptOptionsSetter {
	return func(o *Options) {
		o.outFilename = opt
	}
}

func (o *Options) Validate() error {
	return nil
}
